# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w1_row_1.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w1_row_2.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w1_row_3.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w1_row_4.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w1_row_5.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w1_row_6.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w1_row_7.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w1_row_8.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w1_row_9.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w1_row_10.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w2_row_1.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w2_row_2.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w2_row_3.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w2_row_4.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w2_row_5.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w2_row_6.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w2_row_7.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w2_row_8.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w2_row_9.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/w2_row_10.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/input_vector_q15.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/b1_q15.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/b2_q15.coe
add_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/memory/8_q15.coe
read_verilog -library xil_defaultlib {
  C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/new/uart_rx.v
  C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/new/uart_rx_top.v
  C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/new/z1.v
  C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/new/z2.v
  C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/new/top.v
}
read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_9/blk_mem_gen_9.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_9/blk_mem_gen_9_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_10/blk_mem_gen_10.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_10/blk_mem_gen_10_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_00/blk_mem_gen_00.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_00/blk_mem_gen_00_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_11/blk_mem_gen_11.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_11/blk_mem_gen_11_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_33/blk_mem_gen_33.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_33/blk_mem_gen_33_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_44/blk_mem_gen_44.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_44/blk_mem_gen_44_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_55/blk_mem_gen_55.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_55/blk_mem_gen_55_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_66/blk_mem_gen_66.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_66/blk_mem_gen_66_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_77/blk_mem_gen_77.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_77/blk_mem_gen_77_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_88/blk_mem_gen_88.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_88/blk_mem_gen_88_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_99/blk_mem_gen_99.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_99/blk_mem_gen_99_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_100/blk_mem_gen_100.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_100/blk_mem_gen_100_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_22/blk_mem_gen_22.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_22/blk_mem_gen_22_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_input/blk_mem_gen_input.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_input/blk_mem_gen_input_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/constrs_1/new/arty_a7_100t.xdc
set_property used_in_implementation false [get_files C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/constrs_1/new/arty_a7_100t.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
