# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Vitis_Vivado/z_1/z_1.srcs/sources_1/ip/blk_mem_gen_44/blk_mem_gen_44.xci
# IP: The module: 'blk_mem_gen_44' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vitis_Vivado/z_1/z_1.gen/sources_1/ip/blk_mem_gen_44/blk_mem_gen_44_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_44'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Vitis_Vivado/z_1/z_1.srcs/sources_1/ip/blk_mem_gen_44/blk_mem_gen_44.xci
# IP: The module: 'blk_mem_gen_44' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vitis_Vivado/z_1/z_1.gen/sources_1/ip/blk_mem_gen_44/blk_mem_gen_44_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_44'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
