# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_9/blk_mem_gen_9.xci
# IP: The module: 'blk_mem_gen_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_9/blk_mem_gen_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_9'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.srcs/sources_1/ip/blk_mem_gen_9/blk_mem_gen_9.xci
# IP: The module: 'blk_mem_gen_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Documents/Projects/logic-gate-learner/verilog_code/final_nn/z_1.gen/sources_1/ip/blk_mem_gen_9/blk_mem_gen_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
